on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - tmp

jobs:
  get-info:
    runs-on: ubuntu-latest
    steps:
      - name: Commit author
        run: echo $GITHUB_ACTOR

      - name: Environment (git branch)
        run: echo $GITHUB_REF_NAME

      - name: Project (git repo)
        run: |
          owner_plus_repo=$GITHUB_REPOSITORY
          owner="$GITHUB_REPOSITORY_OWNER/"
          repo=${owner_plus_repo#"$owner"}
          echo $repo

      - name: Commit Long SHA
        run: echo $GITHUB_SHA

      - name: Commit short SHA
        run: |
          short_sha=`echo $GITHUB_SHA | cut -c1-8`
          echo $short_sha

      - name: Date in Postgre format (dd/mm/yyyy hh mm)
        run: |
          postgre_date=`date +"%d/%m/%Y %H %M"`
          echo $postgre_date
